[split-monitor-workspaces]
description = "A plugin to manager multiple monitors"
split-monitor-workspaces = "https://github.com/Duckonaut/split-monitor-workspaces"
output = "split-monitor-workspaces/split-monitor-workspaces.so"
build = ["make all"]

# [Hyprspace]
# description = "A plugin to manager multiple monitors"
# Hyprspace = "https://github.com/KZDKM/Hyprspace"
# output = "Hyprspace/Hyprspace.so"
# build = ["make all"]
